apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-products-app
  labels:
     app: devops-products-app
spec:
  
  selector:
    matchLabels:
      app: devops-products-app
  replicas: 6
  strategy:
    type: RollingUpdate


  template:
    metadata:
      labels:
        app: devops-products-app
    spec:
      containers:
      - name: devops-products-app
        image: aramareddychandana/devops-products-app
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8888