
apiVersion: v1
kind: Service
metadata:
  name: devops-products-app-service
spec:
  selector:
    app: devops-products-app
  type: NodePort
  ports:
  - port: 8888
    nodePort: 30163
    targetPort: 8888